### PR TITLE
feat: apply strikethrough on previous tasks in navigation

### PR DESCRIPTION
**Pull request by boyum**
This PR adds strikethroughs to previous navigation elements in the task navigation. I think it will give some sense of completion when going through the tasks, but it might be annoying?

image

### CODE REVIEW

**Comment by boyum** [comment]
Perhaps we should remove `(this task)`? I'm not sure if it adds any value, even to screen reader users.

**Comment by ingridaase** [comment]
I like the (this task), but I feel like there are a lot of horisontal lines when there are lines both through and under the completed tasks

**Comment by boyum** [comment]
Are you voting "keep as is", @ingridaase? I will not remove the links (thus, the underlines), as I think it's important that it's possible to navigate to previous tasks.

**Comment by ingridaase** [comment]
I vote for the new feature as I like to see clearly what tasks have been completed.

**Review by ingridaase — APPROVED** [review]

**Pull request merged**
